name: Setup Python
description: Setup Python and install dependencies via pip
inputs:
  python-version:
    description: The Python version to use
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: "${{ inputs.python-version }}"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
